spring.application.name=batch-partitioner

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/batch_partitioner
spring.datasource.username=lucas
spring.datasource.password=lucas
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false